---
# Assumes brew bundle has finished and installed all of the software

- hosts: localhost
  name: Deploy dotfiles
  roles:
    # Shell
    - { role: zshell, tags: "zshell" }

    # Color Schemes
    - { role: colors, tags: "colors" }

    # Fonts
    - { role: fonts, tags: "fonts" }

    # Dotfiles
    - { role: stow, tags: "stow" }
    - { role: keybase, tags: "keybase" }

    # MacOS Defaults
    - { role: macos, tags: "macos" }
