---
# Assumes brew bundle has finished and installed all of the software

- name: Deploy dotfiles
  hosts: localhost
  roles:
    # Shell
    - { role: zshell, tags: "zshell" }

    # Color Schemes
    - { role: colors, tags: "colors" }

    # Fonts
    - { role: fonts, tags: "fonts" }

    # Dotfiles
    - { role: stow, tags: "stow" }
    # - { role: keybase, tags: "keybase" }
    - { role: aws-azure-login, tags: "aws-azure-login" }

    # MacOS Defaults
    - { role: macos, tags: "macos" }
