# Assumes brew bundle has finished and installed all of the software

- hosts: localhost
  roles:
    # Shell
    - { role: zshell, tags: "zshell" }

    # Color Schemes
    - { role: colors, tags: "colors" }

    # Dotfiles
    # - { role: stow, tags: "stow" }
