# Assumes brew bundle has finished and installed all of the software

- hosts: localhost
  roles:
    # Shell
    - { role: zshell, tags: "zshell" }

    # Editors
    # - { role: neovim, tags: "neovim" }
    
    # Dotfiles
    # - { role: stow, tags: "stow" }
