---
- name: Change OSX defaults
  become: true
  community.general.osx_defaults:
    domain: "{{ item.domain | default('NSGlobalDomain') }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    host: "{{ item.host | default('null') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ settings }}"
- name: Change OSX defaults not supported by Ansible... yet...
  become: true
  ansible.builtin.command: "{{ item.cmd }}"
  with_items: "{{ unsupported_settings }}"
