---
- name: Change OSX defaults
  become: true
  community.general.osx_defaults:
    domain: "{{ item.domain | default('NSGlobalDomain') }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    host: "{{ item.host | default('null') }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    "{{ settings }}"
