---
- name: Clone oh-my-zsh
  ansible.builtin.git:
    repo: "{{ github }}robbyrussell/oh-my-zsh.git"
    dest: "{{ omzsh_dir }}"
    accept_hostkey: true
    update: false

- name: Check if omzsh is installed
  ansible.builtin.stat:
    path: "{{ omzsh_dir }}"
  register: omzsh

- name: Install oh-my-zsh
  ansible.builtin.shell: "{{ omzsh_dir }}/tools/install.sh"
  when: not omzsh.stat.exists
  changed_when: omzsh.stat.exists

- name: Clone powerlevel10k theme
  ansible.builtin.git:
    repo: "{{ github }}romkatv/powerlevel10k.git"
    dest: "{{ omzsh_themes_dir }}/powerlevel10k"
    accept_hostkey: true

- name: Cloning custom plugins
  ansible.builtin.git:
    repo: "{{ github }}{{ item.value }}/{{ item.key }}.git"
    dest: "{{ omzsh_plugins_dir }}/{{ item.key }}"
    accept_hostkey: true
  with_dict: "{{ omzsh_plugins }}"

- name: Checking for original .zshrc
  ansible.builtin.stat:
    path: "{{ user.home }}/.zshrc"
  register: stat_zshrc

- name: Backing up .zshrc file
  ansible.builtin.command: "mv {{ user.home }}/.zshrc {{ user.home }}/.zshrc.bak"
  args:
    creates: "{{ user.home }}/.zshrc.bak"
  when: stat_zshrc.stat.exists

- name: Create .zshrc
  ansible.builtin.template:
    src: .zshrc.j2
    dest: "{{ user.home }}/.zshrc"
    mode: "0644"

- name: Create .zprofile
  ansible.builtin.template:
    src: .zprofile.j2
    dest: "{{ user.home }}/.zprofile"
    mode: "0644"

- name: Install artii gem
  community.general.gem:
    name: artii
    state: latest
