---
- name: Correct GNUPG permissions
  ansible.builtin.file:
    path: "{{ user.home }}/.gnupg"
    mode: "0700"

- name: Login to Keybase
  ansible.builtin.command:
    cmd: 'keybase --pinentry=none login {{ keybase_username }} --paperkey "{{ keybase_paperkey }}" --devicename {{ansible_hostname}}'

- name: Restart gpg-agent
  ansible.builtin.command:
    cmd: gpgconf --kill gpg-agent

- name: Import PGP Key
  ansible.builtin.shell:
    cmd: 'keybase pgp export -q "{{ keybase_key_id }}" | gpg --import'
  # changed_when: true

- name: Import PGP Private Key
  ansible.builtin.shell:
    cmd: 'keybase --pinentry=none pgp export -q "{{ keybase_key_id }}" --secret | gpg --allow-secret-key-import --import'
  # changed_when: true
  # failed_when: false
