---
- name: Correct GNUPG permissions
  ansible.builtin.file:
    path: '{{ user.home }}/.gnupg'
    mode: '0700'

- name: Login to Keybase
  ansible.builtin.command:
    cmd: "keybase --pinentry=none login {{ keybase_username }} --paperkey \"{{ lookup('ansible.builtin.env', 'KEYBASE_PAPERKEY') }}\" --devicename {{ansible_hostname}}"

- name: Restart gpg-agent
  ansible.builtin.command:
    cmd: gpgconf --kill gpg-agent

- name: Import PGP Key
  ansible.builtin.shell:
    cmd: "keybase pgp export -q \"{{ lookup('ansible.builtin.env', 'KEYBASE_KEY_ID') }}\" | gpg --import"
  # changed_when: true

- name: Import PGP Private Key
  ansible.builtin.shell:
    cmd: "keybase --pinentry=none pgp export -q \"{{ lookup('ansible.builtin.env', 'KEYBASE_KEY_ID') }}\" --secret | gpg --allow-secret-key-import --import"
  # changed_when: true
  # failed_when: false
